#!/usr/bin/env Rscript

.local_libs <- c(Sys.getenv("SC_PCQTL_R_LIBS", unset = ""))
.libPaths(c(.local_libs[nzchar(.local_libs)], .libPaths()))

suppressPackageStartupMessages(library(data.table))

root <- Sys.getenv("SC_PCQTL_FORMAL_COLOC_ROOT", unset = "")
if (!nzchar(root) || !dir.exists(root)) stop("Set SC_PCQTL_FORMAL_COLOC_ROOT.")
work_dir <- Sys.getenv(
  "SC_PCQTL_LOCUSZOOM_WORK_ROOT",
  unset = file.path(root, "10_publication_locuszoom_redesign")
)
out_dir <- file.path(work_dir, "data", "publication_locus_manifest")
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
out_file <- file.path(out_dir, "publication_locus_manifest.tsv")

coloc_file <- file.path(
  root,
  "results/coloc/qtl_gwas_susie_official_finngen_all_finemapped/",
  "qtl_gwas_susie_official_finngen_coloc_summary.tsv"
)
if (!file.exists(coloc_file)) stop("Missing formal coloc summary: ", coloc_file)
coloc <- fread(coloc_file)
coloc[, phenocode := as.character(phenocode)]

# This is the complete final supplementary locus set. The main GIMAP example is
# generated by 01_plot_finngen_style_gimap.R and is intentionally not mixed into
# this supplementary manifest.
wanted <- data.table(
  celltype = c("cd8_et", "cd8_et", "b_in"),
  cluster_id = c("SC_chr11_cluster_002", "SC_chr19_cluster_024", "SC_chr17_cluster_004"),
  qtl_phenotype_id = c("PC2", "PC2", "PC2"),
  phenocode = c("3009542", "3007461", "T2D")
)

eligible <- coloc[
  status == "ok" & qtl_type == "pcQTL",
  .SD[which.max(pph4)],
  by = .(celltype, cluster_id, qtl_phenotype_id, phenocode)
]
manifest <- eligible[wanted, on = .(celltype, cluster_id, qtl_phenotype_id, phenocode), nomatch = 0]
if (nrow(manifest) != nrow(wanted)) {
  found <- manifest[, paste(celltype, cluster_id, qtl_phenotype_id, phenocode, sep = "/")]
  expected <- wanted[, paste(celltype, cluster_id, qtl_phenotype_id, phenocode, sep = "/")]
  stop("Missing final locus rows: ", paste(setdiff(expected, found), collapse = ", "))
}
if (any(manifest$coloc_pass_main != TRUE) || any(manifest$shared_mass_pass != TRUE)) {
  stop("Every final supplementary locus must pass the main coloc and shared-mass QC.")
}

manifest[, `:=`(
  current_strict_coloc_class = "pcQTL_specific_by_cluster_endpoint_max",
  current_strict_signal_group_id = NA_character_,
  caveat = "formal shared-alpha-mass QC passes; pcQTL max PPH4 exceeds same-cluster eQTL max PPH4",
  example_set = "high_confidence_shared_mass_pass",
  plot_priority = 1L,
  figure_id = paste(
    "high_confidence_shared_mass_pass", celltype, cluster_id,
    qtl_phenotype_id, phenocode, sep = "_"
  )
)]

keep <- c(
  "celltype", "cluster_id", "qtl_phenotype_id", "phenocode", "phenotype",
  "current_strict_coloc_class", "current_strict_signal_group_id", "caveat",
  "example_set", "plot_priority", "qtl_type", "figure_id",
  "pph4", "PP.H3.abf", "n_shared_variants", "qtl_signal_index",
  "gwas_signal_index", "qtl_shared_alpha_mass", "gwas_shared_alpha_mass",
  "shared_mass_pass", "qtl_susie_rds", "gwas_susie_rds"
)
missing <- setdiff(keep, names(manifest))
if (length(missing)) stop("Missing formal coloc columns: ", paste(missing, collapse = ", "))
manifest <- manifest[, ..keep]
setnames(manifest, c("pph4", "PP.H3.abf"), c("formal_pph4", "formal_pph3"))
manifest[, final_order := match(phenocode, wanted$phenocode)]
setorder(manifest, final_order)
manifest[, final_order := NULL]

fwrite(manifest, out_file, sep = "\t", quote = FALSE, na = "")
message("Wrote three final supplementary loci to ", out_file)
